################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables
C_SRCS += \
/Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_actq.c \
/Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qk/qk.c \
/Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/qk_port.c

OBJS += \
./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qf_actq.o \
./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk.o \
./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk_port.o

C_DEPS += \
./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qf_actq.d \
./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk.d \
./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk_port.d


# Each subdirectory must supply rules for building sources it contributes
Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qf_actq.o: /Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_actq.c Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H753xx -c -I../../LWIP/App -I../../LWIP/Target -I../../Core/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/BSP/Components/lan8742 -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif/ppp -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/apps -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/priv -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/prot -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/stdc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system/arch -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/ -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/config -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/qpc/RTEF/Real-Time Kernel/qk/qf_actq.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk.o: /Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qk/qk.c Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H753xx -c -I../../LWIP/App -I../../LWIP/Target -I../../Core/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/BSP/Components/lan8742 -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif/ppp -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/apps -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/priv -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/prot -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/stdc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system/arch -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/ -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/config -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/qpc/RTEF/Real-Time Kernel/qk/qk.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk_port.o: /Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/qk_port.c Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H753xx -c -I../../LWIP/App -I../../LWIP/Target -I../../Core/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/BSP/Components/lan8742 -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif/ppp -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/apps -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/priv -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/prot -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/stdc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system/arch -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/ -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/config -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/qpc/RTEF/Real-Time Kernel/qk/qk_port.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-qpc-2f-RTEF-2f-Real-2d-Time-20-Kernel-2f-qk

clean-Middlewares-2f-qpc-2f-RTEF-2f-Real-2d-Time-20-Kernel-2f-qk:
	-$(RM) ./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qf_actq.cyclo ./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qf_actq.d ./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qf_actq.o ./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qf_actq.su ./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk.cyclo ./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk.d ./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk.o ./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk.su ./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk_port.cyclo ./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk_port.d ./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk_port.o ./Middlewares/qpc/RTEF/Real-Time\ Kernel/qk/qk_port.su

.PHONY: clean-Middlewares-2f-qpc-2f-RTEF-2f-Real-2d-Time-20-Kernel-2f-qk
