################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables
C_SRCS += \
/Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_act.c \
/Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_defer.c \
/Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_dyn.c \
/Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_mem.c \
/Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_ps.c \
/Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_qact.c \
/Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_qeq.c \
/Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_qmact.c \
/Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_time.c

OBJS += \
./Middlewares/qpc/RTEF/Framework/qf/qf_act.o \
./Middlewares/qpc/RTEF/Framework/qf/qf_defer.o \
./Middlewares/qpc/RTEF/Framework/qf/qf_dyn.o \
./Middlewares/qpc/RTEF/Framework/qf/qf_mem.o \
./Middlewares/qpc/RTEF/Framework/qf/qf_ps.o \
./Middlewares/qpc/RTEF/Framework/qf/qf_qact.o \
./Middlewares/qpc/RTEF/Framework/qf/qf_qeq.o \
./Middlewares/qpc/RTEF/Framework/qf/qf_qmact.o \
./Middlewares/qpc/RTEF/Framework/qf/qf_time.o

C_DEPS += \
./Middlewares/qpc/RTEF/Framework/qf/qf_act.d \
./Middlewares/qpc/RTEF/Framework/qf/qf_defer.d \
./Middlewares/qpc/RTEF/Framework/qf/qf_dyn.d \
./Middlewares/qpc/RTEF/Framework/qf/qf_mem.d \
./Middlewares/qpc/RTEF/Framework/qf/qf_ps.d \
./Middlewares/qpc/RTEF/Framework/qf/qf_qact.d \
./Middlewares/qpc/RTEF/Framework/qf/qf_qeq.d \
./Middlewares/qpc/RTEF/Framework/qf/qf_qmact.d \
./Middlewares/qpc/RTEF/Framework/qf/qf_time.d


# Each subdirectory must supply rules for building sources it contributes
Middlewares/qpc/RTEF/Framework/qf/qf_act.o: /Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_act.c Middlewares/qpc/RTEF/Framework/qf/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H753xx -c -I../../LWIP/App -I../../LWIP/Target -I../../Core/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/BSP/Components/lan8742 -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif/ppp -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/apps -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/priv -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/prot -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/stdc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system/arch -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/ -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/config -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/qpc/RTEF/Framework/qf/qf_defer.o: /Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_defer.c Middlewares/qpc/RTEF/Framework/qf/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H753xx -c -I../../LWIP/App -I../../LWIP/Target -I../../Core/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/BSP/Components/lan8742 -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif/ppp -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/apps -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/priv -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/prot -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/stdc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system/arch -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/ -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/config -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/qpc/RTEF/Framework/qf/qf_dyn.o: /Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_dyn.c Middlewares/qpc/RTEF/Framework/qf/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H753xx -c -I../../LWIP/App -I../../LWIP/Target -I../../Core/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/BSP/Components/lan8742 -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif/ppp -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/apps -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/priv -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/prot -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/stdc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system/arch -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/ -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/config -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/qpc/RTEF/Framework/qf/qf_mem.o: /Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_mem.c Middlewares/qpc/RTEF/Framework/qf/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H753xx -c -I../../LWIP/App -I../../LWIP/Target -I../../Core/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/BSP/Components/lan8742 -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif/ppp -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/apps -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/priv -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/prot -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/stdc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system/arch -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/ -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/config -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/qpc/RTEF/Framework/qf/qf_ps.o: /Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_ps.c Middlewares/qpc/RTEF/Framework/qf/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H753xx -c -I../../LWIP/App -I../../LWIP/Target -I../../Core/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/BSP/Components/lan8742 -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif/ppp -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/apps -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/priv -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/prot -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/stdc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system/arch -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/ -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/config -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/qpc/RTEF/Framework/qf/qf_qact.o: /Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_qact.c Middlewares/qpc/RTEF/Framework/qf/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H753xx -c -I../../LWIP/App -I../../LWIP/Target -I../../Core/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/BSP/Components/lan8742 -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif/ppp -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/apps -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/priv -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/prot -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/stdc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system/arch -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/ -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/config -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/qpc/RTEF/Framework/qf/qf_qeq.o: /Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_qeq.c Middlewares/qpc/RTEF/Framework/qf/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H753xx -c -I../../LWIP/App -I../../LWIP/Target -I../../Core/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/BSP/Components/lan8742 -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif/ppp -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/apps -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/priv -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/prot -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/stdc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system/arch -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/ -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/config -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/qpc/RTEF/Framework/qf/qf_qmact.o: /Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_qmact.c Middlewares/qpc/RTEF/Framework/qf/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H753xx -c -I../../LWIP/App -I../../LWIP/Target -I../../Core/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/BSP/Components/lan8742 -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif/ppp -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/apps -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/priv -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/prot -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/stdc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system/arch -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/ -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/config -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/qpc/RTEF/Framework/qf/qf_time.o: /Users/s/STM32Cube/Repository/Packs/QuantumLeaps/qpc/8.1.1/src/qf/qf_time.c Middlewares/qpc/RTEF/Framework/qf/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H753xx -c -I../../LWIP/App -I../../LWIP/Target -I../../Core/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/BSP/Components/lan8742 -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif/ppp -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/apps -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/priv -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/lwip/prot -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/netif -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/src/include/compat/stdc -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Middlewares/Third_Party/LwIP/system/arch -I/Users/s/STM32Cube/Repository/STM32Cube_FW_H7_V1.12.1/Drivers/CMSIS/Include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/include -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/qk/gnu/ -I/Users/s/STM32Cube/Repository//Packs/QuantumLeaps/qpc/8.1.1/ports/arm-cm/config -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-qpc-2f-RTEF-2f-Framework-2f-qf

clean-Middlewares-2f-qpc-2f-RTEF-2f-Framework-2f-qf:
	-$(RM) ./Middlewares/qpc/RTEF/Framework/qf/qf_act.cyclo ./Middlewares/qpc/RTEF/Framework/qf/qf_act.d ./Middlewares/qpc/RTEF/Framework/qf/qf_act.o ./Middlewares/qpc/RTEF/Framework/qf/qf_act.su ./Middlewares/qpc/RTEF/Framework/qf/qf_defer.cyclo ./Middlewares/qpc/RTEF/Framework/qf/qf_defer.d ./Middlewares/qpc/RTEF/Framework/qf/qf_defer.o ./Middlewares/qpc/RTEF/Framework/qf/qf_defer.su ./Middlewares/qpc/RTEF/Framework/qf/qf_dyn.cyclo ./Middlewares/qpc/RTEF/Framework/qf/qf_dyn.d ./Middlewares/qpc/RTEF/Framework/qf/qf_dyn.o ./Middlewares/qpc/RTEF/Framework/qf/qf_dyn.su ./Middlewares/qpc/RTEF/Framework/qf/qf_mem.cyclo ./Middlewares/qpc/RTEF/Framework/qf/qf_mem.d ./Middlewares/qpc/RTEF/Framework/qf/qf_mem.o ./Middlewares/qpc/RTEF/Framework/qf/qf_mem.su ./Middlewares/qpc/RTEF/Framework/qf/qf_ps.cyclo ./Middlewares/qpc/RTEF/Framework/qf/qf_ps.d ./Middlewares/qpc/RTEF/Framework/qf/qf_ps.o ./Middlewares/qpc/RTEF/Framework/qf/qf_ps.su ./Middlewares/qpc/RTEF/Framework/qf/qf_qact.cyclo ./Middlewares/qpc/RTEF/Framework/qf/qf_qact.d ./Middlewares/qpc/RTEF/Framework/qf/qf_qact.o ./Middlewares/qpc/RTEF/Framework/qf/qf_qact.su ./Middlewares/qpc/RTEF/Framework/qf/qf_qeq.cyclo ./Middlewares/qpc/RTEF/Framework/qf/qf_qeq.d ./Middlewares/qpc/RTEF/Framework/qf/qf_qeq.o ./Middlewares/qpc/RTEF/Framework/qf/qf_qeq.su ./Middlewares/qpc/RTEF/Framework/qf/qf_qmact.cyclo ./Middlewares/qpc/RTEF/Framework/qf/qf_qmact.d ./Middlewares/qpc/RTEF/Framework/qf/qf_qmact.o ./Middlewares/qpc/RTEF/Framework/qf/qf_qmact.su ./Middlewares/qpc/RTEF/Framework/qf/qf_time.cyclo ./Middlewares/qpc/RTEF/Framework/qf/qf_time.d ./Middlewares/qpc/RTEF/Framework/qf/qf_time.o ./Middlewares/qpc/RTEF/Framework/qf/qf_time.su

.PHONY: clean-Middlewares-2f-qpc-2f-RTEF-2f-Framework-2f-qf
